files:
  - source: /Nos/Assets/Localization/ImagePicker.xcstrings
    translation: /Nos/Assets/Localization/ImagePicker.xcstrings
  - source: /Nos/Assets/Localization/Localizable.xcstrings
    translation: /Nos/Assets/Localization/Localizable.xcstrings
  - source: /Nos/Assets/Localization/Moderation.xcstrings
    translation: /Nos/Assets/Localization/Moderation.xcstrings
  - source: /Nos/Assets/Localization/Reply.xcstrings
    translation: /Nos/Assets/Localization/Reply.xcstrings
